### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Civil** [grobian/carbonserver#28]
Damian asked me to file a bug here so he'll be able to find it not only in history :)
```
2016/05/20 10:04:25 http: panic serving <IP>:45879: runtime error: invalid memory address or nil pointer dereference
goroutine 18390 [running]:
net/http.(*conn).serve.func1(0xc827f04400)
	/usr/lib64/go/src/net/http/server.go:1389 +0xc1
panic(0x8600e0, 0xc820010120)
	/usr/lib64/go/src/runtime/panic.go:426 +0x4e9
github.com/grobian/go-whisper.(*Whisper).Close(0x0)
	/builddir/build/BUILD/carbonserver-20160301_125058-1_88ae672fbd00.el6/gopath/src/github.com/grobian/go-whisper/whisper.go:276 +0x18
main.infoHandler(0x7fdce495ae50, 0xc84989b2b0, 0xc83e1b0700)
	/builddir/build/BUILD/carbonserver-20160301_125058-1_88ae672fbd00.el6/gopath/src/github.com/grobian/carbonserver/main.go:549 +0x3f2
github.com/dgryski/httputil.TimeHandler.func1(0x7fdce495ae50, 0xc84989b2b0, 0xc83e1b0700)
	/builddir/build/BUILD/carbonserver-20160301_125058-1_88ae672fbd00.el6/gopath/src/github.com/dgryski/httputil/times.go:26 +0x70
github.com/dgryski/httputil.TrackConnections.func1(0x7fdce495ae50, 0xc84989b2b0, 0xc83e1b0700)
	/builddir/build/BUILD/carbonserver-20160301_125058-1_88ae672fbd00.el6/gopath/src/github.com/dgryski/httputil/track.go:40 +0xc1
net/http.HandlerFunc.ServeHTTP(0xc8201860b0, 0x7fdce495ae50, 0xc84989b2b0, 0xc83e1b0700)
	/usr/lib64/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc82000ab40, 0x7fdce495ae50, 0xc84989b2b0, 0xc83e1b0700)
	/usr/lib64/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc820094200, 0x7fdce495ae50, 0xc84989b2b0, 0xc83e1b0700)
	/usr/lib64/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc827f04400)
	/usr/lib64/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/lib64/go/src/net/http/server.go:2137 +0x44e
```

**Comment by grobian** [comment]
please tell me if this was/is the problem

**Comment by Civil** [comment]
Yeah, that was a cause of the problem.

**Comment by grobian** [comment]
thanks
